-- Enable pgsodium for encryption
CREATE EXTENSION IF NOT EXISTS pgsodium;

-- Enable moddatetime for updated_at management
CREATE EXTENSION IF NOT EXISTS moddatetime SCHEMA extensions;

-- Create Event Types Table
CREATE TABLE IF NOT EXISTS event_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT NOT NULL UNIQUE,
    length INTEGER NOT NULL DEFAULT 30,
    description TEXT,
    price INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT true,
    user_id UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Availability Table
CREATE TABLE IF NOT EXISTS availability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id),
    event_type_id BIGINT REFERENCES event_types(id),
    days INTEGER[] NOT NULL, -- 0=Sun, 1=Mon, etc.
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Booking Status Enum if not exists
DO $$ BEGIN
    CREATE TYPE booking_status AS ENUM ('pending', 'accepted', 'rejected', 'cancelled');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create Bookings Table
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid UUID DEFAULT gen_random_uuid() UNIQUE,
    event_type_id BIGINT REFERENCES event_types(id),
    user_id UUID REFERENCES auth.users(id), -- The specialist
    patient_id UUID REFERENCES patients(id), -- The client
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    title TEXT,
    description TEXT,
    status booking_status DEFAULT 'pending',
    payment_proof_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Booking Notes Table (Encrypted)
CREATE TABLE IF NOT EXISTS booking_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id BIGINT REFERENCES bookings(id) ON DELETE CASCADE,
    note TEXT, 
    encrypted_note TEXT, 
    created_by UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Triggers for updated_at using moddatetime
CREATE OR REPLACE TRIGGER handle_updated_at_event_types
    BEFORE UPDATE ON event_types
    FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime (updated_at);

CREATE OR REPLACE TRIGGER handle_updated_at_availability
    BEFORE UPDATE ON availability
    FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime (updated_at);

CREATE OR REPLACE TRIGGER handle_updated_at_bookings
    BEFORE UPDATE ON bookings
    FOR EACH ROW EXECUTE PROCEDURE extensions.moddatetime (updated_at);

-- RLS Policies
ALTER TABLE event_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE availability ENABLE ROW LEVEL SECURITY;
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE booking_notes ENABLE ROW LEVEL SECURITY;

-- EVENT TYPES: Public read, Admin write
DROP POLICY IF EXISTS "Public can view active event types" ON event_types;
CREATE POLICY "Public can view active event types" ON event_types FOR SELECT USING (active = true);
DROP POLICY IF EXISTS "Admins can manage event types" ON event_types;
CREATE POLICY "Admins can manage event types" ON event_types FOR ALL USING (auth.uid() = user_id);

-- AVAILABILITY: Public read, Admin write
DROP POLICY IF EXISTS "Public can view availability" ON availability;
CREATE POLICY "Public can view availability" ON availability FOR SELECT USING (true);
DROP POLICY IF EXISTS "Admins can manage availability" ON availability;
CREATE POLICY "Admins can manage availability" ON availability FOR ALL USING (auth.uid() = user_id);

-- BOOKINGS: Users can create, Admins can view/edit
DROP POLICY IF EXISTS "Public can insert bookings" ON bookings;
CREATE POLICY "Public can insert bookings" ON bookings FOR INSERT WITH CHECK (true);
DROP POLICY IF EXISTS "Admins can view their bookings" ON bookings;
CREATE POLICY "Admins can view their bookings" ON bookings FOR SELECT USING (auth.uid() = user_id);

-- BOOKING NOTES: Only Admins/Specialists
DROP POLICY IF EXISTS "Specialists can manage notes" ON booking_notes;
CREATE POLICY "Specialists can manage notes" ON booking_notes FOR ALL USING (
    EXISTS (
        SELECT 1 FROM bookings 
        WHERE bookings.id = booking_notes.booking_id 
        AND bookings.user_id = auth.uid()
    )
);
